services:
  - type: web
    name: experience-remote-signaling
    env: node
    region: oregon
    plan: free
    rootDir: apps/signaling-server
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
